### ISSUE TITLE
2.1 Runtime changes

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#271]
These tasks probably need to be further refined at some point.

Goal: have “start” and “exec” follow the same path. “creates” starts and configure the VM: (ie. POD setup, networking setup). "delete" destroys the VM.
- [x] Add two virtio serial ports for hyperstart communication (https://github.com/01org/cc-oci-runtime/issues/258)
- [ ] Modify “create” to start qemu and then pause when hyperstart is ready (https://github.com/01org/cc-oci-runtime/issues/299)
- [x] Modify "create" to setup the POD/container(s) (https://github.com/01org/cc-oci-runtime/issues/300)
- [x] Modify "create" to do networking setup through hyperstart (https://github.com/01org/cc-oci-runtime/issues/301)
- [x] Modify "create" to spawn cc-shim (https://github.com/01org/cc-oci-runtime/issues/303)
- [x] Modify "start" to use hyperstart EXECCMD command (https://github.com/01org/cc-oci-runtime/issues/302)
- [ ] Implement "exec", which should be very similar to "start" (https://github.com/01org/cc-oci-runtime/issues/18)

**Comment by amshinde** [comment]
Looking at the hyperstart code, looks like we may have to use STARTPOD command in the hypertstart protocol. This parses the json to parse the pod config and containers within,  to parse up a pod, sets up networking/dns, create namespaces (IPC, PID, etc) and sets up   the containers within those namespace with a separate MOUNT namespace.
The NEWCONTAINER expects a pod to be already present, with the pod init started up. It then sets up the container in the namespaces of the pod and executes the process for the container.

**Comment by amshinde** [comment]
Will start looking the runv code to understand the workflow there, though I did notice that runv does not support CREATE command just START.

**Comment by devimc** [comment]
almost merged https://github.com/01org/cc-oci-runtime/pull/365

**Comment by dlespiau** [comment]
2.1 is now merged into master. Closing.
